# Generated by Django 4.2.13 on 2025-12-31 23:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdBookingRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], max_length=20, verbose_name='Duration')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price (EGP)')),
                ('payment_method', models.CharField(choices=[('instapay', 'Instapay'), ('vodafone_cash', 'Vodafone Cash'), ('visa', 'Visa/Mastercard')], max_length=20, verbose_name='Payment Method')),
                ('sender_info', models.CharField(blank=True, help_text='Phone number or account ID used for payment', max_length=100, null=True, verbose_name='Sender Info')),
                ('payment_screenshot', models.ImageField(blank=True, null=True, upload_to='ad_payments/', verbose_name='Payment Screenshot')),
                ('ad_title', models.CharField(blank=True, max_length=200, null=True, verbose_name='Ad Title')),
                ('ad_description', models.TextField(blank=True, null=True, verbose_name='Ad Description')),
                ('ad_image', models.ImageField(blank=True, null=True, upload_to='ad_content/', verbose_name='Ad Image')),
                ('ad_link', models.URLField(blank=True, null=True, verbose_name='Ad Link')),
                ('product_id', models.CharField(blank=True, help_text='Selected product for offer and featured ads', max_length=50, null=True, verbose_name='Product ID')),
                ('special_offer_percentage', models.DecimalField(blank=True, decimal_places=2, help_text='Discount percentage for special offer ads', max_digits=5, null=True, verbose_name='Special Offer Percentage')),
                ('duration_value', models.PositiveIntegerField(blank=True, help_text='Duration multiplier for pricing calculation', null=True, verbose_name='Duration Value')),
                ('total_cost', models.DecimalField(blank=True, decimal_places=2, help_text='Calculated total cost (base price × duration)', max_digits=10, null=True, verbose_name='Total Cost')),
                ('status', models.CharField(choices=[('pending_payment', 'Pending Payment'), ('payment_submitted', 'Payment Submitted'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('active', 'Active'), ('completed', 'Completed'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='payment_submitted', max_length=20, verbose_name='Status')),
                ('admin_notes', models.TextField(blank=True, null=True, verbose_name='Admin Notes')),
                ('start_date', models.DateTimeField(blank=True, null=True, verbose_name='Start Date')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='End Date')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='Approved At')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Completed At')),
            ],
            options={
                'verbose_name': 'Ad Booking Request',
                'verbose_name_plural': 'Ad Booking Requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AdminActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('approve', 'Approve'), ('reject', 'Reject'), ('other', 'Other')], max_length=20)),
                ('description', models.TextField()),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Admin Activity',
                'verbose_name_plural': 'Admin Activities',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='AdminNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('notification_type', models.CharField(choices=[('new_application', 'New Seller Application'), ('system', 'System Notification'), ('report', 'User Report'), ('other', 'Other')], max_length=20)),
                ('is_read', models.BooleanField(default=False)),
                ('link', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AdminPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('products_management', 'Products Management'), ('products_add', 'Add Products'), ('product_approval', 'Product Approval'), ('categories_management', 'Categories Management'), ('variants_management', 'Variants Management'), ('orders_view', 'Orders View'), ('advertising_management', 'Advertising Management'), ('support_tickets', 'Support Tickets'), ('seller_applications', 'Seller Applications'), ('users_management', 'Users Management'), ('admin_management', 'Admin Management'), ('analytics_view', 'Analytics View')], max_length=50, unique=True)),
                ('display_name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Admin Permission',
                'verbose_name_plural': 'Admin Permissions',
                'ordering': ['display_name'],
            },
        ),
        migrations.CreateModel(
            name='AdminRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('display_name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Admin Role',
                'verbose_name_plural': 'Admin Roles',
                'ordering': ['display_name'],
            },
        ),
        migrations.CreateModel(
            name='AdType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('home_slider', 'Home Page Slider'), ('category_slider', 'Category Slider'), ('offer_ad', 'Offer Advertisement'), ('featured_product', 'Featured Product')], max_length=50, unique=True, verbose_name='Ad Type')),
                ('name_ar', models.CharField(max_length=100, verbose_name='Arabic Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('requirements', models.JSONField(blank=True, help_text='JSON field to store requirements for this ad type', null=True, verbose_name='Requirements')),
                ('requires_category', models.BooleanField(default=False, verbose_name='Requires Category Selection')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='Display Order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Ad Type',
                'verbose_name_plural': 'Ad Types',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('image', models.ImageField(upload_to='advertisements/', verbose_name='Image')),
                ('image_url', models.URLField(blank=True, help_text='Use this if image is hosted externally', null=True, verbose_name='External Image URL')),
                ('link_url', models.URLField(blank=True, help_text='URL to navigate when ad is clicked', null=True, verbose_name='Link URL')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Display Order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Advertisement',
                'verbose_name_plural': 'Advertisements',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContentSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_latest_offers', models.BooleanField(default=True, verbose_name='Show Latest Offers')),
                ('show_featured_products', models.BooleanField(default=True, verbose_name='Show Featured Products')),
                ('show_top_artists', models.BooleanField(default=True, verbose_name='Show Top Artists')),
                ('show_top_stores', models.BooleanField(default=True, verbose_name='Show Top Stores')),
                ('show_ads_slider', models.BooleanField(default=True, verbose_name='Show Ads Slider')),
                ('max_products_per_section', models.PositiveIntegerField(default=10, verbose_name='Max Products Per Section')),
                ('max_artists_to_show', models.PositiveIntegerField(default=8, verbose_name='Max Artists to Show')),
                ('max_stores_to_show', models.PositiveIntegerField(default=6, verbose_name='Max Stores to Show')),
                ('max_ads_to_show', models.PositiveIntegerField(default=6, verbose_name='Max Ads to Show')),
                ('ads_rotation_interval', models.PositiveIntegerField(default=4, verbose_name='Ads Rotation Interval (seconds)')),
                ('content_refresh_interval', models.PositiveIntegerField(default=15, verbose_name='Content Refresh Interval (minutes)')),
                ('enable_content_cache', models.BooleanField(default=True, verbose_name='Enable Content Caching')),
                ('cache_duration', models.PositiveIntegerField(default=5, verbose_name='Cache Duration (minutes)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Content Settings',
                'verbose_name_plural': 'Content Settings',
            },
        ),
        migrations.CreateModel(
            name='AdPricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], max_length=20, verbose_name='Duration')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price (EGP)')),
                ('min_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Minimum Price')),
                ('max_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Maximum Price')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ad_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pricing', to='admin_panel.adtype')),
            ],
            options={
                'verbose_name': 'Ad Pricing',
                'verbose_name_plural': 'Ad Pricing',
                'ordering': ['ad_type', 'duration'],
            },
        ),
        migrations.CreateModel(
            name='AdminUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('can_login', models.BooleanField(default=True)),
                ('last_login_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('additional_permissions', models.ManyToManyField(blank=True, help_text='Additional permissions beyond the role', related_name='additional_users', to='admin_panel.adminpermission')),
            ],
            options={
                'verbose_name': 'Admin User',
                'verbose_name_plural': 'Admin Users',
                'ordering': ['user__email'],
            },
        ),
    ]
