# Generated by Django 5.2.3 on 2025-06-20 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adminactivity',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Admin Activity', 'verbose_name_plural': 'Admin Activities'},
        ),
        migrations.AlterField(
            model_name='adminactivity',
            name='action',
            field=models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('approve', 'Approve'), ('reject', 'Reject'), ('other', 'Other')], max_length=20),
        ),
    ]
