# Generated by Django 4.2.13 on 2025-12-31 23:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        ('admin_panel', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='adminuser',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_admins', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='adminuser',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_users', to='admin_panel.adminrole'),
        ),
        migrations.AddField(
            model_name='adminuser',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='admin_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='adminrole',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_roles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='adminrole',
            name='permissions',
            field=models.ManyToManyField(related_name='roles', to='admin_panel.adminpermission'),
        ),
        migrations.AddField(
            model_name='adminactivity',
            name='admin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_activities', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='adbookingrequest',
            name='ad_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_panel.adtype', verbose_name='Ad Type'),
        ),
        migrations.AddField(
            model_name='adbookingrequest',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Required for Category Slider ads', null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.category', verbose_name='Category'),
        ),
        migrations.AddField(
            model_name='adbookingrequest',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ad_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='adpricing',
            unique_together={('ad_type', 'duration')},
        ),
    ]
