# Generated by Django 4.2.13 on 2026-01-06 14:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('total_requests', models.PositiveIntegerField(default=0)),
                ('new_requests', models.PositiveIntegerField(default=0)),
                ('contacted_requests', models.PositiveIntegerField(default=0)),
                ('resolved_requests', models.PositiveIntegerField(default=0)),
                ('closed_requests', models.PositiveIntegerField(default=0)),
                ('avg_response_time_minutes', models.FloatField(blank=True, null=True)),
                ('avg_resolution_time_hours', models.FloatField(blank=True, null=True)),
                ('overdue_requests', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Contact Statistics',
                'verbose_name_plural': 'Contact Statistics',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='ContactRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('contact_number', models.CharField(editable=False, max_length=8, unique=True)),
                ('name', models.CharField(max_length=100, verbose_name='Full Name')),
                ('phone', models.CharField(max_length=20, verbose_name='WhatsApp Phone Number')),
                ('subject', models.CharField(max_length=200, verbose_name='Subject')),
                ('message', models.TextField(verbose_name='Message')),
                ('status', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted via WhatsApp'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='new', max_length=20, verbose_name='Status')),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], default='normal', max_length=10, verbose_name='Priority')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contacted_at', models.DateTimeField(blank=True, null=True, verbose_name='First Contact Time')),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('admin_notes', models.TextField(blank=True, help_text='Internal notes for admin use only', null=True, verbose_name='Admin Notes')),
                ('whatsapp_conversation_id', models.CharField(blank=True, help_text='Reference to WhatsApp conversation', max_length=100, null=True, verbose_name='WhatsApp Conversation ID')),
                ('assigned_to', models.ForeignKey(blank=True, limit_choices_to={'is_staff': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_contacts', to=settings.AUTH_USER_MODEL, verbose_name='Assigned To')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contact_requests', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Contact Request',
                'verbose_name_plural': 'Contact Requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContactNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(verbose_name='Note')),
                ('note_type', models.CharField(choices=[('contact', 'Contact Made'), ('update', 'Status Update'), ('resolution', 'Resolution'), ('internal', 'Internal Note')], default='internal', max_length=15, verbose_name='Note Type')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Author')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='support.contactrequest', verbose_name='Contact Request')),
            ],
            options={
                'verbose_name': 'Contact Note',
                'verbose_name_plural': 'Contact Notes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='contactrequest',
            index=models.Index(fields=['status', 'created_at'], name='support_con_status_0a37e7_idx'),
        ),
        migrations.AddIndex(
            model_name='contactrequest',
            index=models.Index(fields=['phone'], name='support_con_phone_700b44_idx'),
        ),
        migrations.AddIndex(
            model_name='contactrequest',
            index=models.Index(fields=['assigned_to', 'status'], name='support_con_assigne_291b07_idx'),
        ),
        migrations.AddIndex(
            model_name='contactrequest',
            index=models.Index(fields=['priority', 'status'], name='support_con_priorit_7d5fd9_idx'),
        ),
    ]
