# Generated by Django 4.2.13 on 2025-12-31 23:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0002_add_transaction_audit_fields'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='balancesnapshot',
            new_name='wallet_bala_wallet__4649f1_idx',
            old_name='wallet_snap_wallet_date_idx',
        ),
        migrations.RenameIndex(
            model_name='transaction',
            new_name='wallet_tran_idempot_77fbe3_idx',
            old_name='wallet_trans_idemp_idx',
        ),
        migrations.RenameIndex(
            model_name='transaction',
            new_name='wallet_tran_wallet__a053af_idx',
            old_name='wallet_trans_wallet_created_idx',
        ),
        migrations.RenameIndex(
            model_name='transaction',
            new_name='wallet_tran_referen_8e94e0_idx',
            old_name='wallet_trans_ref_idx',
        ),
    ]
