# Generated by Django 4.2.13 on 2026-05-09 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_cart_session_id_alter_cart_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='selected_variants',
            field=models.JSONField(blank=True, help_text='DEPRECATED: Display only. Use variant_id for inventory (Spec 004 C.6)', null=True),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='variant_id',
            field=models.IntegerField(blank=True, help_text='ProductCategoryVariantOption.id for inventory operations (Spec 004 C.6)', null=True),
        ),
    ]
