# Generated by Django 4.2.13 on 2026-01-01 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_add_atomic_order_fields'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='order',
            index=models.Index(
                fields=['user_id', '-created_at'],
                name='orders_order_user_created_at_idx',
            ),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(
                fields=['status'],
                name='orders_order_status_idx',
            ),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(
                fields=['idempotency_key'],
                name='orders_order_idempotency_key_idx',
            ),
        ),
    ]
