# Generated by Django 4.2.13 on 2026-01-01 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_add_order_indexes'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='order',
            new_name='orders_orde_user_id_0ae59f_idx',
            old_name='orders_order_user_created_at_idx',
        ),
        migrations.RenameIndex(
            model_name='order',
            new_name='orders_orde_status_c6dd84_idx',
            old_name='orders_order_status_idx',
        ),
        migrations.RenameIndex(
            model_name='order',
            new_name='orders_orde_idempot_ab5556_idx',
            old_name='orders_order_idempotency_key_idx',
        ),
        migrations.RenameIndex(
            model_name='orderitem',
            new_name='orders_orde_order_i_52f79a_idx',
            old_name='orderitem_order_product_idx',
        ),
        migrations.RenameIndex(
            model_name='orderitem',
            new_name='orders_orde_seller__cbcf6b_idx',
            old_name='orderitem_seller_idx',
        ),
        migrations.RenameIndex(
            model_name='orderitem',
            new_name='orders_orde_variant_164791_idx',
            old_name='orderitem_variant_id_idx',
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('shipped', 'Shipped'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='variant_id',
            field=models.PositiveIntegerField(blank=True, help_text='ID of the product variant ordered', null=True),
        ),
    ]
