# Generated by Django 4.2.13 on 2026-01-01 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_rename_orders_order_user_created_at_idx_orders_orde_user_id_0ae59f_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='order',
            name='orders_orde_user_id_0ae59f_idx',
        ),
    ]
