# Generated by Django 4.2.13 on 2026-01-19 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_order_orders_orde_user_id_0ae59f_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_timeout_at',
            field=models.DateTimeField(blank=True, help_text='Auto-cancel deadline for pending payment orders', null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='item_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', help_text='Fulfillment status of this order item', max_length=20),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='reservation_status',
            field=models.CharField(choices=[('reserved', 'Reserved'), ('released', 'Released'), ('committed', 'Committed')], default='reserved', help_text='Stock reservation state for this item', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending_payment', 'Pending Payment'), ('cod_pending', 'COD Pending'), ('paid', 'Paid'), ('processing', 'Processing'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded'), ('failed', 'Failed')], default='pending_payment', max_length=20),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='variant_id',
            field=models.PositiveIntegerField(blank=True, help_text='ID of product variant ordered', null=True),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status', 'payment_timeout_at'], name='order_timeout_idx'),
        ),
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['item_status'], name='orderitem_status_idx'),
        ),
    ]
