# Generated by Django 4.2.13 on 2026-02-09 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_order_payment_timeout_at_orderitem_item_status_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['variant_id'], name='orderitem_variant_id_idx'),
        ),
    ]

