# Generated by Django 4.2.13 on 2026-05-09 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_add_variant_id_index'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='orderitem',
            name='orderitem_variant_id_idx',
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='variant_id',
            field=models.PositiveIntegerField(blank=True, help_text='ProductCategoryVariantOption.id for variant products (Spec 004 C.3 canonical reference)', null=True),
        ),
    ]
