# Generated by Django 4.2.13 on 2025-12-31 23:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_token', models.CharField(help_text='FCM token for Android, APNs token for iOS', max_length=500, unique=True)),
                ('platform', models.CharField(choices=[('ios', 'iOS'), ('android', 'Android'), ('web', 'Web')], max_length=10)),
                ('device_id', models.CharField(help_text='Unique device identifier', max_length=255)),
                ('app_version', models.CharField(blank=True, max_length=50, null=True)),
                ('device_model', models.CharField(blank=True, max_length=100, null=True)),
                ('os_version', models.CharField(blank=True, max_length=50, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('last_used', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notifications_enabled', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Device',
                'verbose_name_plural': 'Devices',
                'ordering': ['-last_used'],
                'unique_together': {('user', 'device_id', 'platform')},
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('notification_type', models.CharField(choices=[('sale', 'Sale'), ('order_update', 'Order Update'), ('ticket_update', 'Ticket Update'), ('app_update', 'New App Update'), ('new_product', 'New Product from Liked Stores'), ('order', 'Order'), ('payment', 'Payment'), ('system', 'System'), ('promotion', 'Promotion')], max_length=20)),
                ('is_read', models.BooleanField(default=False)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('action_url', models.URLField(blank=True, help_text='URL to redirect when notification is tapped', null=True)),
                ('image_url', models.URLField(blank=True, help_text='Image for notification', null=True)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], default='normal', max_length=10)),
                ('send_push', models.BooleanField(default=True)),
                ('push_sent', models.BooleanField(default=False)),
                ('push_sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('related_object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('related_object_type', models.CharField(blank=True, max_length=50, null=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PushNotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed'), ('pending', 'Pending')], default='pending', max_length=10)),
                ('response_data', models.JSONField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='push_logs', to='notifications.device')),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='push_logs', to='notifications.notification')),
            ],
            options={
                'verbose_name': 'Push Notification Log',
                'verbose_name_plural': 'Push Notification Logs',
                'ordering': ['-sent_at'],
            },
        ),
        migrations.CreateModel(
            name='BulkNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('notification_type', models.CharField(choices=[('sale', 'Sale'), ('order_update', 'Order Update'), ('ticket_update', 'Ticket Update'), ('app_update', 'New App Update'), ('new_product', 'New Product from Liked Stores'), ('order', 'Order'), ('payment', 'Payment'), ('system', 'System'), ('promotion', 'Promotion')], max_length=20)),
                ('target_audience', models.CharField(choices=[('all_users', 'All Users'), ('buyers', 'All Buyers'), ('sellers', 'All Sellers'), ('active_users', 'Active Users (Last 30 Days)'), ('specific_users', 'Specific Users')], max_length=20)),
                ('action_url', models.URLField(blank=True, null=True)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], default='normal', max_length=10)),
                ('schedule_for', models.DateTimeField(blank=True, help_text='Leave empty to send immediately', null=True)),
                ('is_sent', models.BooleanField(default=False)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('recipient_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_bulk_notifications', to=settings.AUTH_USER_MODEL)),
                ('specific_users', models.ManyToManyField(blank=True, help_text="Only used when target_audience is 'specific_users'", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bulk Notification',
                'verbose_name_plural': 'Bulk Notifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
