# Generated by Django 4.2.13 on 2026-02-10 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_active', 'approval_status'], name='product_approved_idx'),
        ),
    ]

