# Generated by Django 4.2.13 on 2026-02-10 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_add_approval_index'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='productcategoryvariantoption',
            index=models.Index(fields=['product', 'is_active'], name='product_variant_option_idx'),
        ),
    ]

