# Generated by Django 5.2.3 on 2025-07-20 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_seller'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('image', models.ImageField(upload_to='advertisements/', verbose_name='Image')),
                ('image_url', models.URLField(blank=True, help_text='Use this if image is hosted externally', null=True, verbose_name='External Image URL')),
                ('link_url', models.URLField(blank=True, help_text='URL to navigate when ad is clicked', null=True, verbose_name='Link URL')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Display Order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Advertisement',
                'verbose_name_plural': 'Advertisements',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContentSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_latest_offers', models.BooleanField(default=True, verbose_name='Show Latest Offers')),
                ('show_featured_products', models.BooleanField(default=True, verbose_name='Show Featured Products')),
                ('show_top_artists', models.BooleanField(default=True, verbose_name='Show Top Artists')),
                ('show_top_stores', models.BooleanField(default=True, verbose_name='Show Top Stores')),
                ('show_ads_slider', models.BooleanField(default=True, verbose_name='Show Ads Slider')),
                ('max_products_per_section', models.PositiveIntegerField(default=10, verbose_name='Max Products Per Section')),
                ('max_artists_to_show', models.PositiveIntegerField(default=8, verbose_name='Max Artists to Show')),
                ('max_stores_to_show', models.PositiveIntegerField(default=6, verbose_name='Max Stores to Show')),
                ('max_ads_to_show', models.PositiveIntegerField(default=6, verbose_name='Max Ads to Show')),
                ('ads_rotation_interval', models.PositiveIntegerField(default=4, verbose_name='Ads Rotation Interval (seconds)')),
                ('content_refresh_interval', models.PositiveIntegerField(default=15, verbose_name='Content Refresh Interval (minutes)')),
                ('enable_content_cache', models.BooleanField(default=True, verbose_name='Enable Content Caching')),
                ('cache_duration', models.PositiveIntegerField(default=5, verbose_name='Cache Duration (minutes)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Content Settings',
                'verbose_name_plural': 'Content Settings',
            },
        ),
    ]
