# Generated by Django 4.2.13 on 2026-05-09 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_add_variant_option_index'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='product',
            name='product_approved_idx',
        ),
        migrations.RemoveIndex(
            model_name='productcategoryvariantoption',
            name='product_variant_option_idx',
        ),
        migrations.AlterField(
            model_name='product',
            name='combination_stocks',
            field=models.JSONField(blank=True, default=dict, help_text='DEPRECATED: Stock quantities for variant combinations. Use ProductCategoryVariantOption.stock_count instead.'),
        ),
    ]
