# Generated by Django 5.2.3 on 2025-07-30 14:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_featuredproduct_productoffer'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='productoffer',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='featuredproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='featured_entries', to='products.product'),
        ),
    ]
